# Brewfile to install all needed homebrew apps.
# Extensively based on mathiasbynen/dotfiles/Brewfile.

# Make sure we’re using the latest Homebrew
update

# Upgrade any already-installed formulae
upgrade

# Install GNU core utilities (those that come with OS X are outdated)
# Don’t forget to add `$(brew --prefix coreutils)/libexec/gnubin` to `$PATH`.
install coreutils
# Install GNU `find`, `locate`, `updatedb`, and `xargs`, g-prefixed
install findutils
# Install Zsh 5
install zsh

# Install wget with IRI support
install wget --enable-iri

# Install more recent versions of some OS X tools
install vim --override-system-vi
tap homebrew/dupes
install homebrew/dupes/grep

# Install other useful binaries and commonly used apps
install ack
install git
install rename
install tmux
install cmus
install fortune
install aspell
install md5sha1sum
install rtorrent
install sshfs
install weechat

# Remove outdated versions from the cellar
cleanup
